//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDCinema.DataAccess.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogEntry
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public string Changes { get; set; }
    }
}
