//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDCinema.DataAccess.Presentation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DDDCinemaReadonly : DbContext
    {
        public DDDCinemaReadonly()
            : base("name=DDDCinemaReadonly")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AuditLogEntry> AuditLogEntries { get; set; }
        public virtual DbSet<LoginAttempt> LoginAttempts { get; set; }
        public virtual DbSet<MailToSend> MailToSends { get; set; }
        public virtual DbSet<Movie> Movies2 { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Seanse> Seanses { get; set; }
        public virtual DbSet<SeatAssignment> SeatAssignments { get; set; }
        public virtual DbSet<SmsToSend> SmsToSends { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ApprovalProcess> ApprovalProcesses { get; set; }
        public virtual DbSet<ApprovalRequest> ApprovalRequests { get; set; }
        public virtual DbSet<Benefit> Benefits { get; set; }
        public virtual DbSet<MoviesToWatch> MoviesToWatches { get; set; }
        public virtual DbSet<PromotionDraft> PromotionDrafts { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<ReceiveCondition> ReceiveConditions { get; set; }
    }
}
