//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDCinema.DataAccess.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempt
    {
        public System.Guid LoginAttemptId { get; set; }
        public bool Succeeded { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string UserRole { get; set; }
        public string Message { get; set; }
        public System.DateTime Time { get; set; }
    }
}
