//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDCinema.DataAccess.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesToWatch
    {
        public System.Guid MovieId { get; set; }
        public System.Guid WatchSpecificMovies_Id { get; set; }
    
        public virtual ReceiveCondition ReceiveCondition { get; set; }
    }
}
