//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDCinema.DataAccess.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> ValidityRange_StartDate { get; set; }
        public Nullable<System.DateTime> ValidityRange_EndDate { get; set; }
        public Nullable<System.Guid> Benefit_Id { get; set; }
        public Nullable<System.Guid> ReceiveCondition_Id { get; set; }
    
        public virtual Benefit Benefit { get; set; }
        public virtual ReceiveCondition ReceiveCondition { get; set; }
    }
}
