//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDCinema.DataAccess.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiveCondition()
        {
            this.MoviesToWatches = new HashSet<MoviesToWatch>();
            this.PromotionDrafts = new HashSet<PromotionDraft>();
            this.Promotions = new HashSet<Promotion>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> RequiredCount { get; set; }
        public Nullable<System.DateTime> ValidityRange_StartDate { get; set; }
        public Nullable<System.DateTime> ValidityRange_EndDate { get; set; }
        public Nullable<System.DateTime> DayToWatch { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoviesToWatch> MoviesToWatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionDraft> PromotionDrafts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
