//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDCinema.DataAccess.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedTimeouts
    {
        public System.Guid Id { get; set; }
        public System.DateTime TimeoutTime { get; set; }
        public string TimeoutType { get; set; }
        public string TimeoutDataJson { get; set; }
    }
}
