//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDCinema.DataAccess.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatAssignment
    {
        public int SeatAssignmentId { get; set; }
        public int SeanseId { get; set; }
        public System.Guid UserId { get; set; }
        public int Row { get; set; }
        public int SeatNumber { get; set; }
    
        public virtual Seanse Seans { get; set; }
    }
}
